# Espanso configuration file
# Espanso settings - https://espanso.org/docs/configuration/#options

# You can use this file to define the global configuration options for espanso.
# These are the parameters that will be used by default on every application,
# but you can also override them on a per-application basis.

# To make customization easier, this file contains some of the commonly used
# parameters. Feel free to uncomment and tune them to fit your needs!

# --- Toggle key -------------------------------------------------------------------------------------------------------

# Customize the key used to disable and enable espanso (when double tapped)
# Available options: CTRL, SHIFT, ALT, CMD, OFF
# You can also specify the key variant, such as LEFT_CTRL, RIGHT_SHIFT, etc...
# You can also disable the toggle key completely with

# toggle_key: ALT
toggle_key: RIGHT_CTRL
# toggle_key: OFF

# --- Injection Backend ------------------------------------------------------------------------------------------------

# Espanso supports multiple ways of injecting text into applications.
# Each of them has its quirks, therefore you may want to change it if you are having problems.
# By default, espanso uses the "Auto" backend which should work well in most cases,
# but you may want to try the "Clipboard" or "Inject" backend in case of issues.
# Forcing all your matches to go through the Clipboard can be less performant/inconvenient than the inject backend.
# If only some of your matches are giving you problems, then use force_clipboard otherwise use full Clipboard backend.
# Because injecting long texts char-by-char is a slow operation, espanso automatically
# uses the clipboard if the text is longer than 'clipboard_threshold' characters.

# clipboard_threshold: 100
# force_clipboard: true
# backend: Clipboard
backend: Inject
fast_inject: true

# --- Auto-restart -----------------------------------------------------------------------------------------------------

# Enable/disable the config auto-reload after a file change is detected.
auto_restart: true

# --- Undo Expansion ---------------------------------------------------------------------------------------------------
undo_backspace: false

# --- Turn off the search bar ------------------------------------------------------------------------------------------
search_shortcut: off

########################################################################################################################
